language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "2.7.13"

addons:
  postgresql: "9.5"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility

env:
  global:
  - VERSION="11.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='transbot@odoo-community.org'
  - secure: "K7mP2tccYr9qicXPpuAYc000j/noV0VmQlnmKJPtNJyFn3MIW24+lkl7TBDop0tSNRayNDzH84CH9TARsYa2nKO0q3MTB7TVseFAtUAPAMvQS7KWwK0HIWadsuVO2TB4ePYEbjPloNoj5JQ2Gf6dl5GMBxXB9V0P9HQeV+5TIkaEE4qUm37HigYOn/QqsmidtPNcYua2kQ2gFHWH30GWZoIojobX4CWpvAgTjvFjlehLf2YaS3cV8eXkwAXJ2xpau16K+COfockYo3AmtTHNmGtqYTboTjMcPtah7dLEu/YPhicmtobjesQYXq7Dy7k2creYepOJk2bFe3YdsQ3VtAXUfyPq++HwO1oY2QgvTPp9ge4cMkpYrU7XAUK2N0Gaj2/vKIi3iacUgTNJz6stRhhXFvx5+l5eZ+z4GgZRGU7M8hToG+5hk3d+529OcaGSUMoJU2yDFCxLb9ixT53ia7in8T1y0DzVmRJyWe6kf+Lg29Z8B1gPfYGa6BTwwIF0iITpkrO7v1xWOsnGc25Nb7BJDMEq8SBHh0JQv7z4X7ac6XGjMhKuVyZJJDCkaNw/BlkOD1DuRDxfySP3P0NH5SgwgDuPzfT8sihr9T973E83OQ4hiQbztHRy+hDct1cFYStSMrgz6uWMkJOmAOPt0yju1LWXrrPLIlgCgh+Ao7s="

  matrix:
  - LINT_CHECK="1"
  - TRANSIFEX="1"
  - TESTS="1" ODOO_REPO="OCA/OCB"
  - TESTS="1" ODOO_REPO="odoo/odoo"

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
